name: Go Release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: read # for checkout

jobs:
  go-release:
    name: Go Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install goreleaser
        working-directory: german-snippets-qdrant
        run: npm i -g @goreleaser/goreleaser

      - name: Release Go binary
        run: goreleaser release
        working-directory: german-snippets-qdrant
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        working-directory: german-snippets-qdrant
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release NPM package
        working-directory: german-snippets-qdrant
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
